#暂未完成
name: CI Pipeline

on: [push, pull_request]

jobs:
  test-iot-converter:
    runs-on: windows-latest  # GUI工具必须用Windows环境
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: cd iot-core && pip install -r requirements.txt
      - run: python -m pytest tests/
      - name: Build GUI
        run: |
          pyinstaller --onefile iot_converter/main.py
          # 这里添加你的GUI构建命令